//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrs11
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Обслуживание.
    /// </summary>
    // *** Start programmer edit section *** (Обслуживание CustomAttributes)

    // *** End programmer edit section *** (Обслуживание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОбслуживаниеE", new string[] {
            "Оператор as \'Оператор\'",
            "Оператор.ФИО as \'ФИО\'",
            "БилетнаяКасса as \'Билетная касса\'",
            "БилетнаяКасса.Наименование as \'Наименование\'",
            "БилетнаяКасса.Адрес as \'Адрес\'",
            "ДатаПроверки as \'Дата проверки\'",
            "ВремяПроверки as \'Время проверки\'",
            "ЧековаяЛента as \'Чековая лента\'",
            "ГотовКРаботе as \'Готов к работе\'"}, Hidden=new string[] {
            "Оператор.ФИО",
            "БилетнаяКасса.Наименование"})]
    [MasterViewDefineAttribute("ОбслуживаниеE", "Оператор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ОбслуживаниеE", "БилетнаяКасса", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ОбслуживаниеL", new string[] {
            "ЧековаяЛента as \'Чековая лента\'",
            "ДатаПроверки as \'Дата проверки\'",
            "ВремяПроверки as \'Время проверки\'",
            "ГотовКРаботе as \'Готов к работе\'",
            "БилетнаяКасса.Наименование as \'Наименование\'",
            "Оператор.ФИО as \'ФИО\'",
            "БилетнаяКасса.Адрес as \'Адрес\'"})]
    public class Обслуживание : ICSSoft.STORMNET.DataObject
    {
        
        private bool fЧековаяЛента;
        
        private System.DateTime fДатаПроверки;
        
        private string fВремяПроверки;
        
        private bool fГотовКРаботе;
        
        private IIS.Kyrs11.БилетнаяКасса fБилетнаяКасса;
        
        private IIS.Kyrs11.Оператор fОператор;
        
        // *** Start programmer edit section *** (Обслуживание CustomMembers)

        // *** End programmer edit section *** (Обслуживание CustomMembers)

        
        /// <summary>
        /// ВремяПроверки.
        /// </summary>
        // *** Start programmer edit section *** (Обслуживание.ВремяПроверки CustomAttributes)

        // *** End programmer edit section *** (Обслуживание.ВремяПроверки CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяПроверки
        {
            get
            {
                // *** Start programmer edit section *** (Обслуживание.ВремяПроверки Get start)

                // *** End programmer edit section *** (Обслуживание.ВремяПроверки Get start)
                string result = this.fВремяПроверки;
                // *** Start programmer edit section *** (Обслуживание.ВремяПроверки Get end)

                // *** End programmer edit section *** (Обслуживание.ВремяПроверки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обслуживание.ВремяПроверки Set start)

                // *** End programmer edit section *** (Обслуживание.ВремяПроверки Set start)
                this.fВремяПроверки = value;
                // *** Start programmer edit section *** (Обслуживание.ВремяПроверки Set end)

                // *** End programmer edit section *** (Обслуживание.ВремяПроверки Set end)
            }
        }
        
        /// <summary>
        /// ГотовКРаботе.
        /// </summary>
        // *** Start programmer edit section *** (Обслуживание.ГотовКРаботе CustomAttributes)

        // *** End programmer edit section *** (Обслуживание.ГотовКРаботе CustomAttributes)
        public virtual bool ГотовКРаботе
        {
            get
            {
                // *** Start programmer edit section *** (Обслуживание.ГотовКРаботе Get start)

                // *** End programmer edit section *** (Обслуживание.ГотовКРаботе Get start)
                bool result = this.fГотовКРаботе;
                // *** Start programmer edit section *** (Обслуживание.ГотовКРаботе Get end)

                // *** End programmer edit section *** (Обслуживание.ГотовКРаботе Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обслуживание.ГотовКРаботе Set start)

                // *** End programmer edit section *** (Обслуживание.ГотовКРаботе Set start)
                this.fГотовКРаботе = value;
                // *** Start programmer edit section *** (Обслуживание.ГотовКРаботе Set end)

                // *** End programmer edit section *** (Обслуживание.ГотовКРаботе Set end)
            }
        }
        
        /// <summary>
        /// ДатаПроверки.
        /// </summary>
        // *** Start programmer edit section *** (Обслуживание.ДатаПроверки CustomAttributes)

        // *** End programmer edit section *** (Обслуживание.ДатаПроверки CustomAttributes)
        public virtual System.DateTime ДатаПроверки
        {
            get
            {
                // *** Start programmer edit section *** (Обслуживание.ДатаПроверки Get start)

                // *** End programmer edit section *** (Обслуживание.ДатаПроверки Get start)
                System.DateTime result = this.fДатаПроверки;
                // *** Start programmer edit section *** (Обслуживание.ДатаПроверки Get end)

                // *** End programmer edit section *** (Обслуживание.ДатаПроверки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обслуживание.ДатаПроверки Set start)

                // *** End programmer edit section *** (Обслуживание.ДатаПроверки Set start)
                this.fДатаПроверки = value;
                // *** Start programmer edit section *** (Обслуживание.ДатаПроверки Set end)

                // *** End programmer edit section *** (Обслуживание.ДатаПроверки Set end)
            }
        }
        
        /// <summary>
        /// ЧековаяЛента.
        /// </summary>
        // *** Start programmer edit section *** (Обслуживание.ЧековаяЛента CustomAttributes)

        // *** End programmer edit section *** (Обслуживание.ЧековаяЛента CustomAttributes)
        public virtual bool ЧековаяЛента
        {
            get
            {
                // *** Start programmer edit section *** (Обслуживание.ЧековаяЛента Get start)

                // *** End programmer edit section *** (Обслуживание.ЧековаяЛента Get start)
                bool result = this.fЧековаяЛента;
                // *** Start programmer edit section *** (Обслуживание.ЧековаяЛента Get end)

                // *** End programmer edit section *** (Обслуживание.ЧековаяЛента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обслуживание.ЧековаяЛента Set start)

                // *** End programmer edit section *** (Обслуживание.ЧековаяЛента Set start)
                this.fЧековаяЛента = value;
                // *** Start programmer edit section *** (Обслуживание.ЧековаяЛента Set end)

                // *** End programmer edit section *** (Обслуживание.ЧековаяЛента Set end)
            }
        }
        
        /// <summary>
        /// Обслуживание.
        /// </summary>
        // *** Start programmer edit section *** (Обслуживание.БилетнаяКасса CustomAttributes)

        // *** End programmer edit section *** (Обслуживание.БилетнаяКасса CustomAttributes)
        [PropertyStorage(new string[] {
                "БилетнаяКасса"})]
        [NotNull()]
        public virtual IIS.Kyrs11.БилетнаяКасса БилетнаяКасса
        {
            get
            {
                // *** Start programmer edit section *** (Обслуживание.БилетнаяКасса Get start)

                // *** End programmer edit section *** (Обслуживание.БилетнаяКасса Get start)
                IIS.Kyrs11.БилетнаяКасса result = this.fБилетнаяКасса;
                // *** Start programmer edit section *** (Обслуживание.БилетнаяКасса Get end)

                // *** End programmer edit section *** (Обслуживание.БилетнаяКасса Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обслуживание.БилетнаяКасса Set start)

                // *** End programmer edit section *** (Обслуживание.БилетнаяКасса Set start)
                this.fБилетнаяКасса = value;
                // *** Start programmer edit section *** (Обслуживание.БилетнаяКасса Set end)

                // *** End programmer edit section *** (Обслуживание.БилетнаяКасса Set end)
            }
        }
        
        /// <summary>
        /// Обслуживание.
        /// </summary>
        // *** Start programmer edit section *** (Обслуживание.Оператор CustomAttributes)

        // *** End programmer edit section *** (Обслуживание.Оператор CustomAttributes)
        [PropertyStorage(new string[] {
                "Оператор"})]
        [NotNull()]
        public virtual IIS.Kyrs11.Оператор Оператор
        {
            get
            {
                // *** Start programmer edit section *** (Обслуживание.Оператор Get start)

                // *** End programmer edit section *** (Обслуживание.Оператор Get start)
                IIS.Kyrs11.Оператор result = this.fОператор;
                // *** Start programmer edit section *** (Обслуживание.Оператор Get end)

                // *** End programmer edit section *** (Обслуживание.Оператор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обслуживание.Оператор Set start)

                // *** End programmer edit section *** (Обслуживание.Оператор Set start)
                this.fОператор = value;
                // *** Start programmer edit section *** (Обслуживание.Оператор Set end)

                // *** End programmer edit section *** (Обслуживание.Оператор Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОбслуживаниеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбслуживаниеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбслуживаниеE", typeof(IIS.Kyrs11.Обслуживание));
                }
            }
            
            /// <summary>
            /// "ОбслуживаниеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбслуживаниеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбслуживаниеL", typeof(IIS.Kyrs11.Обслуживание));
                }
            }
        }
    }
}
