//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrs11
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Покупка билета.
    /// </summary>
    // *** Start programmer edit section *** (ПокупкаБилета CustomAttributes)

    // *** End programmer edit section *** (ПокупкаБилета CustomAttributes)
    [AutoAltered()]
    [Caption("Покупка билета")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПокупкаБилетаE", new string[] {
            "Покупатель as \'Покупатель\'",
            "Покупатель.БанковскийСчет as \'Банковский счет\'",
            "ДатаПоездки as \'Дата поездки\'",
            "Место as \'Место\'"})]
    [MasterViewDefineAttribute("ПокупкаБилетаE", "Покупатель", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class ПокупкаБилета : ICSSoft.STORMNET.DataObject
    {
        
        private int fМесто;
        
        private System.DateTime fДатаПоездки;
        
        private IIS.Kyrs11.Покупатель fПокупатель;
        
        private IIS.Kyrs11.ПокупИлиВозвБ fПокупИлиВозвБ;
        
        // *** Start programmer edit section *** (ПокупкаБилета CustomMembers)

        // *** End programmer edit section *** (ПокупкаБилета CustomMembers)

        
        /// <summary>
        /// ДатаПоездки.
        /// </summary>
        // *** Start programmer edit section *** (ПокупкаБилета.ДатаПоездки CustomAttributes)

        // *** End programmer edit section *** (ПокупкаБилета.ДатаПоездки CustomAttributes)
        public virtual System.DateTime ДатаПоездки
        {
            get
            {
                // *** Start programmer edit section *** (ПокупкаБилета.ДатаПоездки Get start)

                // *** End programmer edit section *** (ПокупкаБилета.ДатаПоездки Get start)
                System.DateTime result = this.fДатаПоездки;
                // *** Start programmer edit section *** (ПокупкаБилета.ДатаПоездки Get end)

                // *** End programmer edit section *** (ПокупкаБилета.ДатаПоездки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупкаБилета.ДатаПоездки Set start)

                // *** End programmer edit section *** (ПокупкаБилета.ДатаПоездки Set start)
                this.fДатаПоездки = value;
                // *** Start programmer edit section *** (ПокупкаБилета.ДатаПоездки Set end)

                // *** End programmer edit section *** (ПокупкаБилета.ДатаПоездки Set end)
            }
        }
        
        /// <summary>
        /// Место.
        /// </summary>
        // *** Start programmer edit section *** (ПокупкаБилета.Место CustomAttributes)

        // *** End programmer edit section *** (ПокупкаБилета.Место CustomAttributes)
        public virtual int Место
        {
            get
            {
                // *** Start programmer edit section *** (ПокупкаБилета.Место Get start)

                // *** End programmer edit section *** (ПокупкаБилета.Место Get start)
                int result = this.fМесто;
                // *** Start programmer edit section *** (ПокупкаБилета.Место Get end)

                // *** End programmer edit section *** (ПокупкаБилета.Место Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупкаБилета.Место Set start)

                // *** End programmer edit section *** (ПокупкаБилета.Место Set start)
                this.fМесто = value;
                // *** Start programmer edit section *** (ПокупкаБилета.Место Set end)

                // *** End programmer edit section *** (ПокупкаБилета.Место Set end)
            }
        }
        
        /// <summary>
        /// Покупка билета.
        /// </summary>
        // *** Start programmer edit section *** (ПокупкаБилета.Покупатель CustomAttributes)

        // *** End programmer edit section *** (ПокупкаБилета.Покупатель CustomAttributes)
        [PropertyStorage(new string[] {
                "Покупатель"})]
        [NotNull()]
        public virtual IIS.Kyrs11.Покупатель Покупатель
        {
            get
            {
                // *** Start programmer edit section *** (ПокупкаБилета.Покупатель Get start)

                // *** End programmer edit section *** (ПокупкаБилета.Покупатель Get start)
                IIS.Kyrs11.Покупатель result = this.fПокупатель;
                // *** Start programmer edit section *** (ПокупкаБилета.Покупатель Get end)

                // *** End programmer edit section *** (ПокупкаБилета.Покупатель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупкаБилета.Покупатель Set start)

                // *** End programmer edit section *** (ПокупкаБилета.Покупатель Set start)
                this.fПокупатель = value;
                // *** Start programmer edit section *** (ПокупкаБилета.Покупатель Set end)

                // *** End programmer edit section *** (ПокупкаБилета.Покупатель Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kyrs11.ПокупИлиВозвБ.
        /// </summary>
        // *** Start programmer edit section *** (ПокупкаБилета.ПокупИлиВозвБ CustomAttributes)

        // *** End programmer edit section *** (ПокупкаБилета.ПокупИлиВозвБ CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ПокупИлиВозвБ"})]
        public virtual IIS.Kyrs11.ПокупИлиВозвБ ПокупИлиВозвБ
        {
            get
            {
                // *** Start programmer edit section *** (ПокупкаБилета.ПокупИлиВозвБ Get start)

                // *** End programmer edit section *** (ПокупкаБилета.ПокупИлиВозвБ Get start)
                IIS.Kyrs11.ПокупИлиВозвБ result = this.fПокупИлиВозвБ;
                // *** Start programmer edit section *** (ПокупкаБилета.ПокупИлиВозвБ Get end)

                // *** End programmer edit section *** (ПокупкаБилета.ПокупИлиВозвБ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупкаБилета.ПокупИлиВозвБ Set start)

                // *** End programmer edit section *** (ПокупкаБилета.ПокупИлиВозвБ Set start)
                this.fПокупИлиВозвБ = value;
                // *** Start programmer edit section *** (ПокупкаБилета.ПокупИлиВозвБ Set end)

                // *** End programmer edit section *** (ПокупкаБилета.ПокупИлиВозвБ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПокупкаБилетаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПокупкаБилетаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПокупкаБилетаE", typeof(IIS.Kyrs11.ПокупкаБилета));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ПокупкаБилета.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПокупкаБилета CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПокупкаБилета CustomAttributes)
    public class DetailArrayOfПокупкаБилета : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kyrs11.DetailArrayOfПокупкаБилета members)

        // *** End programmer edit section *** (IIS.Kyrs11.DetailArrayOfПокупкаБилета members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ПокупкаБилета by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ПокупкаБилета.
        /// </summary>
        public DetailArrayOfПокупкаБилета(IIS.Kyrs11.ПокупИлиВозвБ fПокупИлиВозвБ) : 
                base(typeof(ПокупкаБилета), ((ICSSoft.STORMNET.DataObject)(fПокупИлиВозвБ)))
        {
        }
        
        public IIS.Kyrs11.ПокупкаБилета this[int index]
        {
            get
            {
                return ((IIS.Kyrs11.ПокупкаБилета)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kyrs11.ПокупкаБилета dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
